### ISSUE TITLE
Add-on can not be configured--Config panel error when starting add-on

### ISSUE THREAD

**Issue by XLTechie** [ruifontes/agenda-for-NVDA#1]
Add-on Version: 2023.05.30

An NVDA error sound plays when the add-on is started in NVDA alphas. This is in the log:

```
ERROR - globalPluginHandler.initialize (04:56:26.690) - MainThread (9588):
Error initializing global plugin <class 'globalPlugins.agenda.GlobalPlugin'>
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 32, in initialize
  File "...\agenda\globalPlugins\agenda\__init__.py", line 44, in __init__
    gui.NVDASettingsDialog.categoryClasses.append(AgendaSettingsPanel)
NameError: name 'AgendaSettingsPanel' is not defined
```

**Comment by ruifontes** [comment]
Corrected on version 2023.05.31
